### PR TITLE
Added the Shelf class and its first sub-class

### PR DESCRIPTION
**Pull request by jmwright**
@julianstirling I roughed something in just so that I can see if it is the right direction. Let me know what you think.

### CODE REVIEW

**Comment by jmwright** [comment]
>  I am wondering if the class wants to sit in nimble_build_system/cad next to shelf_builder.py.

I can restructure this PR to put the Shelf class there, and merge the other parts of the original Shelf class in the orchestrator directory into the new Shelf class.

**Comment by julianstirling** [comment]
Sounds perfect!

**Comment by jmwright** [comment]
@julianstirling I noticed that `width` was used being used in device.py where the database had called the dimension `length`. I had multiple discussions about dimension naming during the hackathon, and it felt like we always went in circles. It would be good if we can clearly define our reference dimensions (length, width, height, depth, etc) with maybe even a diagram so that we can standardize on that.

**Comment by julianstirling** [comment]
100% agree it is like the shelf/tray debate.

The other thing is we need to agree what to do for non-cube devices as some just get a diameter symbol. I don't think there is much scope for validating in NocoDB, so maybe we make some rules and validate the data and report back to the database team anything that can't be validated?

A diagram would be great.

**Comment by jmwright** [comment]
The following is what I expected, where the dimension names follow the axes. However, the database uses the term `LengthMm` whereas the `Device.py` class uses `Width`.

dimensions

If we can figure out what we want to standarize on, I can put a diagram in a readme in the `cad` directory.

**Comment by julianstirling** [comment]
To me `length` is the ambiguous term in a rack system. I think height is clearly z, width is parallel to the front of the rack. Depth perpendicular to the front of the rack.

I'd say that we choose a system that makes sense in the code, update the json file with a script. And later we can ask for the database to be update. The database is there to hold data for the orchestrator, so I think the orchestrator should choose the names.

**Comment by julianstirling** [comment]
FYI if you want to check the linting locally. You can install `pylint` with `pip`.

The two commands are

     ./lint_test.py -t py

and

    ./lint_test.py -t cadquery

The only difference is they use different RC files. The RC file for CadQuery scripts is less strict enforcing uppercase global names, and also understands `show_object()`

**Comment by jmwright** [comment]
> I think height is clearly z, width is parallel to the front of the rack. Depth perpendicular to the front of the rack.

Ok, moving my perspective to the rack's dimensions helps. I think the diagram below shows what you are saying, which seems to be the way you set the dimensions up in device.py. I understand why now. If you agree, I can clean this diagram up and get it placed in a readme in the `cad` directory.

dimensions

> FYI if you want to check the linting locally. You can install pylint with pip.

I fixed the linting check for the CadQuery code, but to fix the `py` linting completely, it looks like I would need to touch a few files outside of my area, and I'm afraid that will create merge conflicts. There are also some linting errors that I cannot fix yet because I have not finished merging the two shelf.py files. I will try to get that straightened out this week.

**Comment by julianstirling** [comment]
Looks food. I may make a diagram with an image of the rack in it to make it really clear?

Agreed that we can fix the linting errors later rather than in this PR, as it wasn't create by this PR.

**Comment by jmwright** [comment]
> I may make a diagram with an image of the rack in it to make it really clear?

What I was visualizing was a diagram that had both a screenshot of a shelf and a screenshot of a rack with the reference arrows on both.

**Comment by jmwright** [comment]
@julianstirling Thoughts on this diagram?

nimble_dimension_name_diagram

**Comment by julianstirling** [comment]
I love it to bits 😻

**Comment by jmwright** [comment]
@julianstirling I have added a readme with the dimension name diagram in it.

I have also added a `tests` directory because I needed a way to test my changes at a higher level without relative and circular imports. I have used `pytest` because it is what I am most familiar with, but I can change it, if desired. Is the initial test that I have created using the right entry point into the Nimble orchestrator/build system?

**Comment by julianstirling** [comment]
Looks great. Yeah the test is doing the correct thing, except I wouldn't write too many unit tests until the in progress changes of mine are in as the configuration is changing to be less complex and based on assemblies and sub-assemblies. 

What you ave done here will help me finish off what I am doing as I need to talk to something to get docs from. Maybe we get this merged in its current state. I'll try and fix my stuff tomorrow morning to a state where it isn't perfect but can also be merged, and then we can both carry on what we are doing?

**Comment by jmwright** [comment]
@julianstirling Sounds good to me

**Comment by julianstirling** [comment]
I'll review it in the morning

**Comment by jmwright** [comment]
@julianstirling Before I had to quit for the day, I remember thinking that the path to the STL will be broken in the generated markdown because it prepends the `build` directory. I didn't write that markdown code, I copied and modified it from the old `Shape` class. Feel free to push a fix before merging, or you can wait and I'll fix it in another PR when I make a pass through that code.

**Review by julianstirling — APPROVED** [review]
The only thing I would really change is I'd probably prefer the orientation diagram for the readme to sit in `<repo-root>/assets/img/` just to keep the images together.

Going to merge as is, we can tidy that later if you agree.

**Pull request merged**
