### PR TITLE
Updating for breaking changes in CadOrchechestrator v0.1.0, tweak requirements

### PR DESCRIPTION
**Pull request by julianstirling**
Small PR just to use new, more flexible configuration structure from CadOrchestrator v0.1.0

### CODE REVIEW

**Comment by jmwright** [comment]
@julianstirling I don't understand why CI is trying to install CadQuery 2.3 all of a sudden. It should be installing 2.4. I'll have to dig into that.

**Comment by jmwright** [comment]
@julianstirling The ca-cli tag has a bad reference. Working on a fix now.

**Comment by julianstirling** [comment]
Can you release cq-cli on pypi under a different name. Such as `cq-cli-python` I know it isn't idea. But it does create a standard easy yo manage reference

**Comment by jmwright** [comment]
I tried a couple of experiments, and PyPI didn't seem to like any variant with cq-cli in it (including _ substituted for -). Not sure if it's a bug in their name filtering system or what. I can check again.

**Comment by julianstirling** [comment]
I believe there is a rule to to stop anything too closely named to something else. Even though it is not online using a name checker `cqcli` seems taken so I think that blocks anything that is the same when removing non-alphanumeric characters. Adding `-python` may help.

**Comment by jmwright** [comment]
I fixed it with the tag for now, and will experiment more with the PyPI name.

**Comment by jmwright** [comment]
I changed the name on PyPI to `cadquery-cli` and it seems to work fine. The one test is still failing though.

**Comment by julianstirling** [comment]
I think this is now ready for review.

**Review by jmwright — APPROVED** [review]
Looks good, thanks @julianstirling !

**Pull request merged**
