### PR TITLE
Improve GitHub Actions

### PR DESCRIPTION
**Pull request by julianstirling**
The goal of this PR is to improve the GitHub Actions to

* [x] Stop attempting to deploy to pages when not on master
* [x] Lint python code

### CODE REVIEW

**Comment by julianstirling** [comment]
Hi @jmwright 
I have added two lining jobs. One lints Python files that are not directly run by cq-cli. The other lints these CadQuery scripts.

The reason they are linted separately is they require different pylint rc files.  For CadQuery I have made a custom rc file that:
* Sets `show_object` as additional built in.
* Expects constants to be *snake_case* rather than *UPPER_CASE* to allow parameters to be sit in lower case
* Allows redefining from variables from outer scope. Normally I'd be against this, but it does seem the most sensible behaviour for passing the cad query parameters into a function.

Running lint-test.py is documented in the help you get when you run `./lint-test.py -h`

## Merging when failing!?

The CI is failing because the code has some issues that the linter has found. I think it makes sense to merge this now so that we have linting happening. And then we can open another PR to fix errors.

**Review by jmwright — APPROVED** [review]
@julianstirling I think this looks fine to merge. I am not overly familiar with pylint since all the projects I'm involved in use black, but linters are all designed to do the same job and work in similar ways.

Are you planning to fix all the linter errors, or do you want me to create a PR for the CadQuery lint errors?

**Comment by julianstirling** [comment]
Thanks @jmwright

I think the main difference from black to pylint is that black automatically formats your code (unless they added more features since I last checked). Pylint doesn't actually edit the code, it just complains if things are bad. But it is designed to do far more checks to warn you about possible bugs and unsafe code.

I'm in the middle of doing a first pass fixing some things now. Once I have done that there may be some more things to fix

**Comment by jmwright** [comment]
> black automatically formats your code

Many projects run `black --diff --check .` to check the code without editing it. This is especially useful in CI.

**Comment by julianstirling** [comment]
Thanks, but I think black still only checks the formatting. Not things like if variables are undefined?

**Pull request merged**
