### PR TITLE
Smart documentation for any Nimble configuration

### PR DESCRIPTION
**Pull request by julianstirling**
This is a large ongoing project that will soon be merged into the master Nimble branch.

Once complete our documentation website will:
* Allow you to configure your Nimble
* Automatically generate the specific STLs you need for your custom configuration
* Automatically generate an instruction manual for your custom configuration, including customised renders of the assembly steps.

This work is [funded by NLNet](https://nlnet.nl/project/HardwareManuals/)

---

This PR is a combination of a series of other PRs into the smart_doc branch:

- <https://github.com/Wakoma/nimble/pull/50>
-  <https://github.com/Wakoma/nimble/pull/48>
-  <https://github.com/Wakoma/nimble/pull/22>
-  <https://github.com/Wakoma/nimble/pull/16>
-  <https://github.com/Wakoma/nimble/pull/14>
-  <https://github.com/Wakoma/nimble/pull/12>
-  <https://github.com/Wakoma/nimble/pull/11>
-  <https://github.com/Wakoma/nimble/pull/10>
-  <https://github.com/Wakoma/nimble/pull/9>

### CODE REVIEW

**Comment by David-ksturnpike** [comment]
suggestion for the shelves, could we use Velcro in addition or in place of zip ties?  I suggest this as if you use zip ties and want to change the device on the shelf then you would have to cut the zip tie in order to change the device out.  however, if Velcro was used then all you would have to do would be to undo the Velcro and then change the device out and then re Velcro the device to the shelf.

**Comment by julianstirling** [comment]
@David-ksturnpike Good point on the suitability front, it is worth checking whether Velcro ties fit through.

I think what is used will come partially down to local context. If the device is likely to have significant rough transport, I would expect standard zip-ties are less likely to fail. Availability in remote locations may also be challenging. But I agree, where practical they are more sustainable and less annoying.

As this MR is going to become quite large, this specific point may get lost in the discussion. Might be worth opening an issue about velcro ties so we don't loose it?

**Comment by David-ksturnpike** [comment]
issue has been raised

**Comment by julianstirling** [comment]
@jmwright and I are on a call and have both decided it is time to get this merged

**Pull request merged**
